### ISSUE TITLE
feat: 連合する鯖を選べるようにする

### ISSUE THREAD

**Issue by arisumilkland** [arisumilkland/mimermoe#35]
# 原因
違法になりかねない機能・ユーザーのことを全く考えられていない機能・道徳心がない機能が実装されそうなため。
https://github.com/misskey-dev/misskey/issues/12343

**Comment by tai-cha** [comment]
ちなみにmisskey自体にこれが入る以前に悪意のある実装やフォークではすでにフォロワー限定やダイレクトは見れてしまいます

**Comment by arisumilkland** [comment]
それは存じてますが、その機能が全体で有効になった際に起きる問題について理解してますか？

**Comment by tai-cha** [comment]
理解していますし、わたしは賛成の立場ではないです（なのでそもそも入ったものみたいに言われているのが:confused:になっただけです）

**Comment by arisumilkland** [comment]
気に入らないと言われたのでやめる
